### ISSUE TITLE
Fallback fonts on SDL2

### ISSUE THREAD

**Issue by laurence-flwls** [libsdl-org/SDL_ttf#338] opened 2024-02-14 10:24 UTC
Hi, I'm creating a terminal emulator in SDL2 and finding a lot of characters aren't present in a particular type-face (examples below).

I'd like to be able to define fallback fonts to cover instances were glyphs aren't available in the default type face.

After a bit of searching online, the only reference to this issue I could find was a Github issue from 2019 which sounded like a fix was soon to be merged. However, unless I've missed something obvious in the docs, I cannot find _how_ implement that.

eg:
my terminal emulator (SDL2) vs iTerm2 -- under the `DEC Special graphics and line drawing` heading:

![image](https://github.com/libsdl-org/SDL_ttf/assets/121872654/e78d69c3-2e3a-458a-885d-090b448d88ff)
![image](https://github.com/libsdl-org/SDL_ttf/assets/121872654/778fb28a-ca72-4ac4-90c6-c31437e9f0e4)

**Comment by slouken** [comment] 2024-02-14 21:38
Could you link the GitHub issue you found? I'm not seeing it.

**Comment by laurence-flwls** [comment] 2024-02-14 21:48
@slouken my apologies, it wasn't an official SDL repo: https://github.com/grimfang4/SDL_FontCache/issues/29

**Comment by laurence-flwls** [comment] 2024-02-14 22:30
So if we ignore the unrelated project, what would be the recommended way to solve my problem here? Because it's a text heavy application, a performant way to validate the glyphs would be preferable.

There is another curveball here though, I'm writing this terminal emulator in Go (golang). I do have some experience in C and older versions of C++ too so I can work my way through a C solution and port it to Go if needed. The only reason I favour Go these days is because it's faster (for me at least) to prototype code.

**Comment by slouken** [comment] 2024-06-10 15:51
Duplicate of #362, which has better repro steps.

**Closed by slouken** 2024-06-10 15:51 UTC
