### ISSUE TITLE
Proper UTF-16 and characters outside the BMP support

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_ttf#79] opened 2021-02-11 05:45 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Windows 10, x86_64

# Comments on the original bug report:

On 2018-09-03 07:21:42 +0000, pjz wrote:

> I propose a patch with added proper UTF-16 and characters outside the BMP support, which extends the fix to the bug # 3762. The code can be found at <https://github.com/acmepjz/SDL_ttf/tree/utf16-fix>.
> 
> * Change the UCS-2 code to UTF-16 code, which allows characters outside the BMP range
> 
> * Change various public functions (TTF_GlyphIsProvided, TTF_GlyphMetrics, TTF_RenderGlyph_***, etc.) to accept Uint32 for character instead of Uint16
> 
> * Also added a UTF-32 to UTF-8 conversion routine (which is only used in TTF_RenderGlyph_***)

**Comment by slouken** [comment] 2024-01-15 20:26
Duplicate of https://github.com/libsdl-org/SDL_ttf/issues/230

**Closed by slouken** 2024-01-15 20:26 UTC
Labels: enhancement
