### ISSUE TITLE
Harbuzz compilation fails because of Wcast-function-type-strict

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL_ttf#320] opened 2023-12-20 20:58 UTC
for the record, Harfbuzz wouldn't compile because of warn-error "cast-function-type-strict' in hb-ft.cc
with ndk-r26

fixed by: 
```
diff --git a/src/hb.hh b/src/hb.hh
index 54191c0a4..efc461978 100644
--- a/src/hb.hh
+++ b/src/hb.hh
@@ -133,6 +133,7 @@
 #pragma GCC diagnostic ignored "-Wstrict-aliasing"
 #pragma GCC diagnostic ignored "-Wtype-limits"
 #pragma GCC diagnostic ignored "-Wc++11-compat" // only gcc raises it
+#pragma GCC diagnostic ignored "-Wcast-function-type-strict"
 #endif
```

**Comment by WalkerWhite** [comment] 2023-12-21 22:32
I was just coming here to note this error. I can confirm the above solution works.

It would be preferable to configure this in Android.mk, as the CMake files work just fine for Android.  However, ndk-build refuses to recognize -Wno-cast-function-type-strict.

**Comment by slouken** [comment] 2023-12-24 14:48
@1bsyl, can you make a PR against the 2.9.1-SDL branch of https://github.com/harfbuzz?

**Comment by sezero** [comment] 2023-12-24 16:12
> against the 2.9.1-SDL branch of https://github.com/harfbuzz?

Actually, the current SDL2 and SDL3 branches use 8.1.1-SDL branch of harfbuzz -- it seems like `.gitmodules` wasn't updated to reflect that when upgrade happened.

**Comment by sezero** [comment] 2023-12-27 23:27
> > against the 2.9.1-SDL branch of https://github.com/harfbuzz?
> 
> Actually, the current SDL2 and SDL3 branches use 8.1.1-SDL branch of harfbuzz -- it seems like `.gitmodules` wasn't updated to reflect that when upgrade happened.

I just updated harfbuzz branch name in .gitmodules for both SDL2 and SDL3

**Comment by sezero** [comment] 2024-01-03 16:42
@1bsyl: We are vendoring version 8.1.1 of harfbuzz, and that warning is
already ignored in 8.1.1.

I believe the issue you experienced was due to .gitmodules being out-of-
date, which was fixed as of commit https://github.com/libsdl-org/SDL_ttf/commit/303c2801322b03ee0ccdb652b70f237b229408b5 (https://github.com/libsdl-org/SDL_ttf/commit/5762821745b7be9c839e72becb9dd27109a47e91 for SDL2 branch),
therefore closing this ticket. If I am mistaken, please re-open.

**Closed by sezero** 2024-01-03 16:42 UTC
