### ISSUE TITLE
build script enhancements

### ISSUE THREAD

**Issue by Xeverous** [libsdl-org/SDL_ttf#122] opened 2021-02-25 23:22 UTC
I have trouble building the project using MinGW-w64 toolchain.

For CMake approach:

- CMake script is written so that it only expects CMake-based builds, it searches for `*.cmake` files but I have only `*.pc` files for pkg-config (I could make a PR to make a CMake option to use `pkg_check_modules()` instead of `FindPackage()` - please let me know if you could accept such change)
- CMake script contains outdated SDL_ttf version information

For configure approach:

- The script works but incorrectly attempts to check for OpenGL support which results in OpenGL unnecessarily disabled

`configure.log`:

```
configure:13738: checking for OpenGL support
configure:13758: gcc -o conftest.exe -g -O2 -IC:/usr/include/freetype2 -IC:/usr/include/libpng16 -IC:/mingw64/mingw64/include -Dmain=SDL_main -IC:/usr/SDL2-2.0.10/x86_64-w64-mingw32/include/SDL2   conftest.c  -LC:/usr/lib -LC:/mingw64/mingw64/lib -lfreetype -lpng16 -lz -lbz2 -LC:/usr/SDL2-2.0.10/x86_64-w64-mingw32/lib -lmingw32 -lSDL2main -lSDL2 -mwindows -lGL >&5
C:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lGL
collect2.exe: error: ld returned 1 exit status
```

The library is named `opengl32`, not `GL` on Windows.

**Comment by sezero** [comment] 2021-02-26 00:39
Speaking for configure: it works for me:
```
configure:13768: checking for OpenGL support
configure:13788: x86_64-w64-mingw32-gcc -o conftest.exe -g -O2 -I/opt/dev/include/freetype2   -Dmain=SDL_main -I/opt/dev/include/SDL2     conftest.c  -L/opt/dev/lib -lfreetype   -mwindows -L/opt/dev/lib -lmingw32 -lSDL2main -lSDL2   -lopengl32 >&5
configure:13788: $? = 0
configure:13795: result: yes
```
I am building from the git repo. See this line in configure.in:
https://github.com/libsdl-org/SDL_ttf/blob/main/configure.in#L110
It does set gl library to opengl32 for windows builds.

**Comment by Xeverous** [comment] 2021-02-26 11:20
Indeed, there is a such case, my `$host` is `x86_64-pc-mingw64` and it does match. The lines you wrote are

https://github.com/libsdl-org/SDL_ttf/blob/11722a2bb4335d489d724c08cfdbb45f97d07aa7/configure#L13026-L13030

but my problem is on these lines:

https://github.com/libsdl-org/SDL_ttf/blob/11722a2bb4335d489d724c08cfdbb45f97d07aa7/configure.in#L132-L138

https://github.com/libsdl-org/SDL_ttf/blob/11722a2bb4335d489d724c08cfdbb45f97d07aa7/configure#L13760-L13766

These hardcode `-lGL` for any host. I don't know all of the shell language details, but putting some echo statements proved that I hit both lines 13029 and 13764.

**Comment by sezero** [comment] 2021-02-26 13:12
That's a switch statement where `mingw*)` has top-level priority whereas `*)` is
everything else that doesn't match anything:  How is it possible that you hit both?

**Comment by Xeverous** [comment] 2021-02-26 13:27
No idea. I will try latest commit but first I need to build newer SDL.

**Comment by sezero** [comment] 2021-02-26 13:28
> That's a switch statement where `mingw*)` has top-level priority whereas `*)` is
> everything else that doesn't match anything: How is it possible that you hit both?

One thing that comes to my mind is that, if you are building from a git clone
it may try to autoreconf itself (type `git status` to see if there are any changes to
tree) and failures _might_ (or might not) happen. To prevent that do:
```
git clone https://github.com/libsdl-org/SDL_ttf.git
cd SDL_ttf && touch aclocal.m4 Makefile.in configure
```
and then run configure.

**Comment by Xeverous** [comment] 2021-02-26 13:30
It can not, because I don't have autoconf installed.

**Comment by Xeverous** [comment] 2021-02-26 16:16
OK, I abandoned the autotools approach, I found out that every project in this dependency tree

- SDL_ttf
  - SDL
  - freetype
    - libpng
      - zlib
    - bzip2
    - zlib

has CMake support, so I rebuilt everything using CMake.

So as of now, this issue is only about this:

https://github.com/libsdl-org/SDL_ttf/blob/11722a2bb4335d489d724c08cfdbb45f97d07aa7/CMakeLists.txt#L51-L53

verson number in CMake recipe is outdated

**Comment by sezero** [comment] 2021-02-26 16:41
https://github.com/libsdl-org/SDL_ttf/commit/b45d3c63735cd21d44d45294e92256934b3387f2 should make cmake version info up-to-date and matching autotools.

@slouken: can you reproduce the reported autotools issues?

**Comment by slouken** [comment] 2022-05-23 20:28
No, I can't reproduce this. Since @Xeverous switched to CMake and his issue is fixed, I'll go ahead and close this bug.

**Closed by slouken** 2022-05-23 20:28 UTC
