### ISSUE TITLE
Download Page not found - buildozer kivymd

### ISSUE THREAD

**Issue by rodrigoquiles** [libsdl-org/SDL_ttf#248] opened 2022-12-27 00:08 UTC
Page download not found
https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.0.15/SDL2_ttf-2.0.15.tar.gz

**Comment by Peter-Port** [comment] 2023-01-01 10:11
Same here.
For me, it's not possible to run buildozer on github or colab without getting the following error:



[INFO]:    Downloading sdl2_ttf from https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.0.15/SDL2_ttf-2.0.15.tar.gz
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1312, in <module>
    main()
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 734, in __init__
    getattr(self, command)(args)
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 212, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 482, in build_recipes
    recipe.download_if_necessary()
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 348, in download_if_necessary
    self.download()
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 398, in download
    self.download_file(self.versioned_url, filename)
  File "/github/workspace/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 202, in download_file
    urlretrieve(url, target, report_hook)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Download failed: HTTP Error 404: Not Found; retrying in 1 second(s)...Download failed: HTTP Error 404: Not Found; retrying in 2 second(s)...Download failed: HTTP Error 404: Not Found

**Comment by Peter-Port** [comment] 2023-01-01 12:47
Now i see what the problem is. In buildozer i wrote: 

requirements = sdl2_ttf==2.0.15

Thats not ok anymore, just use sdl2_ttf==2.20.0 or maybe no special version-number.

**Comment by madebr** [comment] 2023-01-01 13:19
I've added all 2.0.15 archives from https://www.libsdl.org/projects/SDL_ttf/release/ to https://github.com/libsdl-org/SDL_ttf/releases/tag/release-2.0.15.

@slouken I don't know whether it is intentional to give members of @libsdl-org/a-team these permissions?

**Closed by madebr** 2023-01-01 13:19 UTC
